// NB: Android Studio can't find the imports; this does not affect the
// actual build since Gradle can find them just fine.
// remove after upgrading to 'com.android.tools.build:gradle:8.1.0' (AGP 8.1)
import com.android.tools.profgen.ArtProfileKt
import com.android.tools.profgen.ArtProfileSerializer
import com.android.tools.profgen.DexFile

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'kotlin-kapt'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader -> localProperties.load(reader) }
}

android {

    defaultConfig {
        applicationId "com.blockchain.bitcoin.wallet"
        compileSdk compile_sdk_version
        minSdkVersion min_sdk_version
        targetSdkVersion compile_sdk_version
        versionCode 1
        versionName "0.1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        kapt {
            arguments {
                arg("room.schemaLocation", "$projectDir/schemas".toString())
                arg("room.incremental", true)
            }
        }
        vectorDrawables.useSupportLibrary = true
        lintOptions {
            checkReleaseBuilds false
        }

        resValue "string", "companyWebPageLink", "https://horizontalsystems.io"
        resValue "string", "appWebPageLink", "https://unstoppable.money"
        resValue "string", "analyticsLink", "https://unstoppable.money/analytics"
        resValue "string", "appGithubLink", "https://github.com/horizontalsystems/unstoppable-wallet-android"
        resValue "string", "appTwitterLink", "https://twitter.com/UnstoppableByHS"
        resValue "string", "appTelegramLink", "https://t.me/unstoppable_announcements"
        resValue "string", "appRedditLink", "https://www.reddit.com/r/UNSTOPPABLEWallet/"
        resValue "string", "reportEmail", "support.unstoppable@protonmail.com"
        resValue "string", "releaseNotesUrl", "https://api.github.com/repos/horizontalsystems/unstoppable-wallet-android/releases/tags/"
        resValue "string", "walletConnectAppMetaDataName", "Unstoppable"
        resValue "string", "walletConnectAppMetaDataUrl", "unstoppable.money"
        resValue "string", "walletConnectAppMetaDataIcon", "https://raw.githubusercontent.com/horizontalsystems/HS-Design/master/PressKit/UW-AppIcon-on-light.png"
        resValue "string", "accountsBackupFileSalt", "unstoppable"
    }

    buildFeatures {
        compose true
        viewBinding true
    }

    signingConfigs {
        appCenter {
            storeFile file("./test.keystore")
            storePassword localProperties.getProperty('keystore.storePassword', '')
            keyAlias localProperties.getProperty('keystore.keyAlias', '')
            keyPassword localProperties.getProperty('keystore.keyPassword', '')
        }
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            resValue "string", "twitterBearerToken", localProperties.getProperty('debug.twitterBearerToken', '')
            resValue "string", "cryptoCompareApiKey", localProperties.getProperty('debug.cryptoCompareApiKey', '')
            resValue "string", "uniswapGraphUrl", "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2"
            resValue "string", "infuraProjectId", localProperties.getProperty('debug.infuraProjectId', '')
            resValue "string", "infuraSecretKey", localProperties.getProperty('debug.infuraSecretKey', '')
            resValue "string", "etherscanKey", localProperties.getProperty('debug.etherscanKey', '')
            resValue "string", "bscscanKey", localProperties.getProperty('debug.bscscanKey', '')
            resValue "string", "polygonscanKey", localProperties.getProperty('debug.polygonscanKey', '')
            resValue "string", "snowtraceApiKey", localProperties.getProperty('debug.snowtraceApiKey', '')
            resValue "string", "optimisticEtherscanApiKey", localProperties.getProperty('debug.optimisticEtherscanApiKey', '')
            resValue "string", "arbiscanApiKey", localProperties.getProperty('debug.arbiscanApiKey', '')
            resValue "string", "gnosisscanApiKey", localProperties.getProperty('debug.gnosisscanApiKey', '')
            resValue "string", "ftmscanApiKey", localProperties.getProperty('debug.ftmscanApiKey', '')
            resValue "string", "defiyieldProviderApiKey", localProperties.getProperty('debug.defiyieldProviderApiKey', '')
            resValue "string", "is_release", "false"
            resValue "string", "guidesUrl", "https://raw.githubusercontent.com/horizontalsystems/blockchain-crypto-guides/develop/index.json"
            resValue "string", "faqUrl", "https://raw.githubusercontent.com/horizontalsystems/Unstoppable-Wallet-Website/master/src/faq.json"
            resValue "string", "coinsJsonUrl", "https://raw.githubusercontent.com/horizontalsystems/cryptocurrencies/master/coins.json"
            resValue "string", "providerCoinsJsonUrl", "https://raw.githubusercontent.com/horizontalsystems/cryptocurrencies/master/provider.coins.json"
            resValue "string", "marketApiBaseUrl", "https://api-dev.blocksdecoded.com"
            resValue "string", "marketApiKey", localProperties.getProperty('debug.marketApiKey', '')
            resValue "string", "openSeaApiKey", localProperties.getProperty('debug.openSeaApiKey', '')
            resValue "string", "walletConnectV2Key", localProperties.getProperty('debug.walletConnectV2Key', '')
            resValue "string", "solscanApiKey", localProperties.getProperty('debug.solscanApiKey', '')
            resValue "string", "trongridApiKey", localProperties.getProperty('debug.trongridApiKey', '')
            resValue "string", "udnApiKey", localProperties.getProperty('debug.udnApiKey', '')
            resValue "string", "oneInchApiKey", localProperties.getProperty('debug.oneInchApiKey', '')
        }

        appcenterdebug {
            initWith debug
            defaultConfig.versionCode System.getenv("BUILD_NUMBER")?.toInteger() ?: defaultConfig.versionCode
            applicationIdSuffix ".dev.appcenter"
            signingConfig signingConfigs.appCenter
            matchingFallbacks = ['debug']
        }

        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            resValue "string", "twitterBearerToken", localProperties.getProperty('release.twitterBearerToken', '')
            resValue "string", "cryptoCompareApiKey", ""
            resValue "string", "uniswapGraphUrl", "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2"
            resValue "string", "infuraProjectId", localProperties.getProperty('release.infuraProjectId', '')
            resValue "string", "infuraSecretKey", localProperties.getProperty('release.infuraSecretKey', '')
            resValue "string", "etherscanKey", localProperties.getProperty('release.etherscanKey', '')
            resValue "string", "bscscanKey", localProperties.getProperty('release.bscscanKey', '')
            resValue "string", "polygonscanKey", localProperties.getProperty('release.polygonscanKey', '')
            resValue "string", "snowtraceApiKey", localProperties.getProperty('release.snowtraceApiKey', '')
            resValue "string", "optimisticEtherscanApiKey", localProperties.getProperty('release.optimisticEtherscanApiKey', '')
            resValue "string", "arbiscanApiKey", localProperties.getProperty('release.arbiscanApiKey', '')
            resValue "string", "gnosisscanApiKey", localProperties.getProperty('release.gnosisscanApiKey', '')
            resValue "string", "ftmscanApiKey", localProperties.getProperty('release.ftmscanApiKey', '')
            resValue "string", "defiyieldProviderApiKey", localProperties.getProperty('release.defiyieldProviderApiKey', '')
            resValue "string", "is_release", "true"
            resValue "string", "guidesUrl", "https://raw.githubusercontent.com/horizontalsystems/blockchain-crypto-guides/v1.2/index.json"
            resValue "string", "faqUrl", "https://raw.githubusercontent.com/horizontalsystems/Unstoppable-Wallet-Website/v1.3/src/faq.json"
            resValue "string", "coinsJsonUrl", "https://raw.githubusercontent.com/horizontalsystems/cryptocurrencies/v0.21/coins.json"
            resValue "string", "providerCoinsJsonUrl", "https://raw.githubusercontent.com/horizontalsystems/cryptocurrencies/v0.21/provider.coins.json"
            resValue "string", "marketApiBaseUrl", "https://api.blocksdecoded.com"
            resValue "string", "marketApiKey", localProperties.getProperty('release.marketApiKey', '')
            resValue "string", "openSeaApiKey", localProperties.getProperty('release.openSeaApiKey', '')
            resValue "string", "walletConnectV2Key", localProperties.getProperty('release.walletConnectV2Key', '')
            resValue "string", "solscanApiKey", localProperties.getProperty('release.solscanApiKey', '')
            resValue "string", "trongridApiKey", localProperties.getProperty('release.trongridApiKey', '')
            resValue "string", "udnApiKey", localProperties.getProperty('release.udnApiKey', '')
            resValue "string", "oneInchApiKey", localProperties.getProperty('release.oneInchApiKey', '')
        }

        appcenterrelease {
            initWith release
            defaultConfig.versionCode System.getenv("BUILD_NUMBER")?.toInteger() ?: defaultConfig.versionCode
            applicationIdSuffix ".appcenter"
            signingConfig signingConfigs.appCenter
            matchingFallbacks = ['release']
        }

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        resources {
            pickFirsts += ['META-INF/atomicfu.kotlin_module']
            excludes += ['META-INF/INDEX.LIST', 'META-INF/DEPENDENCIES', 'META-INF/LICENSE.md', 'META-INF/NOTICE.md']
        }
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.3'
    }
    namespace 'io.horizontalsystems.bankwallet'
    lint {
        disable 'LogNotTimber'
    }

    configurations.configureEach { c ->
        c.resolutionStrategy.dependencySubstitution {
            substitute module('org.bouncycastle:bcprov-jdk15to18:1.68') using module('org.bouncycastle:bcprov-jdk15on:1.65')
            substitute module('com.google.protobuf:protobuf-java:3.6.1') using module('com.google.protobuf:protobuf-javalite:3.21.1')
            substitute module('net.jcip:jcip-annotations:1.0') using module('com.github.stephenc.jcip:jcip-annotations:1.0-1')

            substitute module('com.tinder.scarlet:scarlet:0.1.12') using module('com.github.WalletConnect.Scarlet:scarlet:1.0.0')
            substitute module('com.tinder.scarlet:websocket-okhttp:0.1.12') using module('com.github.WalletConnect.Scarlet:websocket-okhttp:1.0.0')
            substitute module('com.tinder.scarlet:stream-adapter-rxjava2:0.1.12') using module('com.github.WalletConnect.Scarlet:stream-adapter-rxjava2:1.0.0')
            substitute module('com.tinder.scarlet:message-adapter-gson:0.1.12') using module('com.github.WalletConnect.Scarlet:message-adapter-gson:1.0.0')
            substitute module('com.tinder.scarlet:lifecycle-android:0.1.12') using module('com.github.WalletConnect.Scarlet:lifecycle-android:1.0.0')
        }
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:$appcompat_version"
    implementation "androidx.constraintlayout:constraintlayout:$constraint_version"
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    // use -ktx for Kotlin
    // alternatively - just LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    // alternatively - Lifecycles only (no ViewModel or LiveData).
    //     Support library depends on this lightweight import
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.fragment:fragment-ktx:$fragment_ktx_version"
    implementation "androidx.preference:preference-ktx:1.2.1"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

    //Splash screen
    implementation "androidx.core:core-splashscreen:1.0.1"

    //AppWidgets
    implementation 'androidx.glance:glance-appwidget:1.0.0'

    // Room
    def room_version = '2.6.0'
    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    implementation "androidx.room:room-rxjava2:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    // alternately - if using Java8, use the following instead of compiler
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    // optional - ReactiveStreams support for LiveData
    implementation "androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycle_version"


    implementation "com.google.android.material:material:$material_version"

    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    // Because RxAndroid releases are few and far between, it is recommended you also
    // explicitly depend on RxJava's latest version for bug fixes and new features.
    // (see https://github.com/ReactiveX/RxJava/releases for latest 2.x.x version)
    implementation "io.reactivex.rxjava2:rxjava:$rxjava_version"
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation "androidx.biometric:biometric:$biometric_version"

    implementation 'com.atlassian.commonmark:commonmark:0.17.0'
    implementation "io.noties.markwon:core:4.6.2"

    // ViewPager circle indicator
    implementation 'me.relex:circleindicator:2.1.6'

    //Custom tabs, chrome
    implementation "androidx.browser:browser:1.7.0"

    // Navigation component
    implementation "androidx.navigation:navigation-fragment-ktx:$navigation_ktx_version"
    implementation "androidx.navigation:navigation-ui-ktx:$navigation_ktx_version"

    //Compose Navigation
    implementation "androidx.navigation:navigation-compose:$navigation_ktx_version"
    implementation "com.google.accompanist:accompanist-navigation-animation:$accompanist_version"

    api 'com.journeyapps:zxing-android-embedded:4.3.0'

    // WorkManager Kotlin
    def work_version = "2.8.1"
    implementation "androidx.work:work-runtime-ktx:$work_version"
    // WorkManager RxJava2 support
    implementation "androidx.work:work-rxjava2:$work_version"

    //def leakCanary = 'com.squareup.leakcanary:leakcanary-android:2.10'
    //appcenterdebugImplementation leakCanary
    //debugImplementation leakCanary

    // Wallet kits
    implementation 'com.github.horizontalsystems:bitcoin-kit-android:bc62893'
    implementation 'com.github.horizontalsystems:ethereum-kit-android:94bb971'
    implementation 'com.github.horizontalsystems:blockchain-fee-rate-kit-android:1d3bd49'
    implementation 'com.github.horizontalsystems:binance-chain-kit-android:7e4d7c0'
    implementation 'com.github.horizontalsystems:market-kit-android:0059cac'
    implementation 'com.github.horizontalsystems:solana-kit-android:5cc6e81'
    implementation 'com.github.horizontalsystems:tron-kit-android:67f8d53'
    // Zcash SDK
    implementation "cash.z.ecc.android:zcash-android-sdk:2.0.1"
    implementation("io.github.binance:binance-connector-java:3.0.0rc2") {
        exclude group: "org.bouncycastle", module: "bcprov-jdk18on"
    }

    // WalletConnect V2
    implementation(platform("com.walletconnect:android-bom:1.15.0"))
    implementation 'com.walletconnect:sign'
    implementation 'com.walletconnect:android-core'

    // Unstoppable Domains
    implementation 'com.github.unstoppabledomains:resolution-java:v7.1.0'

    // Ethereum Name Service
    implementation "org.web3j:core:4.9.0"

    implementation 'com.twitter.twittertext:twitter-text:3.1.0'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.7.3'

    // UI modules

    implementation project(':core')
    implementation project(':components:icons')
    implementation project(':components:chartview')
    implementation platform('androidx.compose:compose-bom:2023.10.01')
    // Integration with activities
    implementation 'androidx.activity:activity-compose:1.8.1'
    // Compose Material Design
    implementation "androidx.compose.material:material"
    implementation "androidx.compose.material3:material3:1.2.0-alpha11"
    // Animations
    implementation "androidx.compose.animation:animation"
    // Tooling support (Previews, etc.)
    implementation "androidx.compose.ui:ui-tooling"
    // Integration with ViewModels
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2'

    implementation "androidx.compose.runtime:runtime-livedata"

    def coil_version = "2.4.0"
    implementation "io.coil-kt:coil-compose:$coil_version"
    implementation "io.coil-kt:coil-svg:$coil_version"
    implementation("io.coil-kt:coil-gif:$coil_version")

    // When using a AppCompat theme
    implementation "com.google.accompanist:accompanist-appcompat-theme:$accompanist_version"
    implementation "com.google.accompanist:accompanist-flowlayout:$accompanist_version"
    implementation "com.google.accompanist:accompanist-permissions:$accompanist_version"

    // UI Tests
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"

    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // optional - Test helpers for LiveData
    testImplementation "junit:junit:$junit_version"
    testImplementation "androidx.arch.core:core-testing:2.2.0"
    testImplementation "org.mockito:mockito-core:3.3.3"
    testImplementation 'com.nhaarman:mockito-kotlin-kt1.1:1.6.0'
    testImplementation 'org.powermock:powermock-api-mockito2:2.0.7'
    testImplementation 'org.powermock:powermock-module-junit4:2.0.7'

    // Spek
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:2.0.9"
    testRuntimeOnly "org.spekframework.spek2:spek-runner-junit5:2.0.9"
    testRuntimeOnly "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    //Android Tor
    implementation 'info.guardianproject:tor-android:0.4.7.14'
    implementation 'info.guardianproject:jtorctl:0.4.5.7'

    api 'com.jaredrummler:android-shell:1.0.0'
    api 'com.offbynull.portmapper:portmapper:2.0.5'
    implementation("com.applovin:applovin-sdk:12.0.0")
    implementation("com.google.android.gms:play-services-ads-identifier:18.0.1")
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

// fixes reproducible builds (fixes difference in assets/dexopt/baseline.profm)
// more info https://issuetracker.google.com/issues/231837768
// remove after upgrading to 'com.android.tools.build:gradle:8.1.0' (AGP 8.1)
project.afterEvaluate {
    tasks.each { task ->
        if (task.name.startsWith("compile") && task.name.endsWith("ReleaseArtProfile")) {
            task.doLast {
                outputs.files.each { file ->
                    if (file.name.endsWith(".profm")) {
                        println("Sorting ${file} ...")
                        def version = ArtProfileSerializer.valueOf("METADATA_0_0_2")
                        def profile = ArtProfileKt.ArtProfile(file)
                        def keys = new ArrayList(profile.profileData.keySet())
                        def sortedData = new LinkedHashMap()
                        // xxx ignore not resolved classes; gradle can manage
                        Collections.sort keys, new DexFile.Companion()
                        keys.each { key -> sortedData[key] = profile.profileData[key] }
                        new FileOutputStream(file).with {
                            write(version.magicBytes$profgen)
                            write(version.versionBytes$profgen)
                            version.write$profgen(it, sortedData, "")
                        }
                    }
                }
            }
        }
    }
}
